"use client";
import {
  BadgeCheck,
  Bone,
  Camera,
  ChartSpline,
  SplinePointer,
  CircleDot,
  CloudOff,
  Crop,
  DraftingCompass,
  Download,
  Eye,
  EyeOff,
  Eraser,
  FlipHorizontal2,
  FlipVertical2,
  GitCompare,
  HandGrab,
  History,
  Layers,
  Lock,
  LockOpen,
  Maximize2,
  Menu,
  MessageSquare,
  Minus,
  MoveDown,
  MoveLeft,
  MoveRight,
  MoveUp,
  Package,
  Paintbrush,
  PencilLine,
  Plus,
  Redo2,
  RefreshCcw,
  RotateCcw,
  RotateCw,
  RulerDimensionLine,
  Save,
  Scaling,
  Slice,
  SlidersHorizontal,
  Spline,
  LineSquiggle,
  Target,
  Trash2,
  Undo2,
  Upload,
  X,
  ZoomIn,
  ZoomOut,
} from "lucide-react";

const ICON_COMPONENTS = {
  draw: PencilLine,
  freeLine: LineSquiggle,
  pan: HandGrab,
  cut: Slice,
  centerFinder: Target,
  axisBuilder: Bone,
  guideBuilder: RulerDimensionLine,
  zoomIn: ZoomIn,
  zoomOut: ZoomOut,
  fit: Maximize2,
  rotateLeft: RotateCcw,
  rotateRight: RotateCw,
  flipH: FlipHorizontal2,
  flipV: FlipVertical2,
  resetCrop: Crop,
  scale: Scaling,
  preset: RulerDimensionLine,
  saveCal: BadgeCheck,
  trash: Trash2,
  clear: Eraser,
  brush: Paintbrush,
  lock: Lock,
  unlock: LockOpen,
  reset: RefreshCcw,
  upload: Upload,
  camera: Camera,
  target: Target,
  menu: Menu,
  close: X,
  moveLeft: MoveLeft,
  moveRight: MoveRight,
  save: Save,
  history: History,
  undo: Undo2,
  redo: Redo2,
  eye: Eye,
  eyeOff: EyeOff,
  settings: SlidersHorizontal,
  annotation: MessageSquare,
  layers: Layers,
  angle: DraftingCompass,
  circle: CircleDot,
  hka: ChartSpline,
  compare: GitCompare,
  export: Download,
  package: Package,
  cloudOff: CloudOff,
  minus: Minus,
  plus: Plus,
  moveUp: MoveUp,
  moveDown: MoveDown,
};

export default function Icon({ name, className = "h-4 w-4" }) {
  const IconComponent = ICON_COMPONENTS[name];
  if (!IconComponent) return null;
  return (
    <IconComponent className={className} strokeWidth={2} aria-hidden="true" />
  );
}
